-- MySQL Script generated by MySQL Workbench
-- Mon Nov 29 20:54:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema COVID_MG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COVID_MG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COVID_MG` DEFAULT CHARACTER SET utf8 ;
USE `COVID_MG` ;

-- -----------------------------------------------------
-- Table `COVID_MG`.`Localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`Localidade` (
  `MUNIC_RESIDENCIA` VARCHAR(45) NOT NULL,
  `COD_IBGE` INT NULL,
  `URS` VARCHAR(45) NULL,
  `MICRO` VARCHAR(45) NULL,
  `MACRO` VARCHAR(45) NULL,
  PRIMARY KEY (`MUNIC_RESIDENCIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COVID_MG`.`tabela_fatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`tabela_fatos` (
  `idtabela_fatos` INT NOT NULL,
  `NUM_CASOS` INT NULL,
  `NUM_INTERNADOS` INT NULL,
  `NUM_OBITOS` INT NULL,
  `NUM_RECUPERADOS` INT NULL,
  `DATA` VARCHAR(45) NULL,
  `Localidade_MUNIC_RESIDENCIA` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtabela_fatos`, `Localidade_MUNIC_RESIDENCIA`),
  INDEX `fk_tabela_fatos_Localidade_idx` (`Localidade_MUNIC_RESIDENCIA` ASC) VISIBLE,
  CONSTRAINT `fk_tabela_fatos_Localidade`
    FOREIGN KEY (`Localidade_MUNIC_RESIDENCIA`)
    REFERENCES `COVID_MG`.`Localidade` (`MUNIC_RESIDENCIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
