-- MySQL Script generated by MySQL Workbench
-- Fri Nov 26 18:32:32 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema COVID_MG
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema COVID_MG
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `COVID_MG` DEFAULT CHARACTER SET utf8 ;
USE `COVID_MG` ;

-- -----------------------------------------------------
-- Table `COVID_MG`.`Obitos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`Obitos` (
  `id_Obitos` INT NOT NULL,
  `NUM_OBITOS` INT NULL,
  PRIMARY KEY (`id_Obitos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COVID_MG`.`Casos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`Casos` (
  `idCasos` INT NOT NULL,
  `NUM_CASOS` INT NULL,
  PRIMARY KEY (`idCasos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COVID_MG`.`Recuperados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`Recuperados` (
  `idRecuperados` INT NOT NULL,
  `NUM_RECUPERADOS` INT NULL,
  PRIMARY KEY (`idRecuperados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COVID_MG`.`Internados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`Internados` (
  `idInternados` INT NOT NULL,
  `NUM_INTERNADOS` INT NULL,
  PRIMARY KEY (`idInternados`))
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `COVID_MG`.`Localidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`Localidade` (
  `idLocalidade` INT NOT NULL,
  `MUNIC_RESIDENCIA` VARCHAR(45) NULL,
  `COD_IBGE` INT NULL,
  `MICRO` VARCHAR(45) NULL,
  `MACRO` VARCHAR(45) NULL,
  PRIMARY KEY (`idLocalidade`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `COVID_MG`.`tabela_fatos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `COVID_MG`.`tabela_fatos` (
  `idtabela_fatos` INT NOT NULL,
  `DATA` VARCHAR(45) NULL,
  `URS` VARCHAR(45) NULL,
  `Casos_idCasos` INT NOT NULL,
  `Localidade_idLocalidade` INT NOT NULL,
  `Recuperados_idRecuperados` INT NOT NULL,
  `Obitos_id_Obitos` INT NOT NULL,
  `Internados_idInternados` INT NOT NULL,
  PRIMARY KEY (`idtabela_fatos`, `Casos_idCasos`, `Localidade_idLocalidade`, `Recuperados_idRecuperados`, `Obitos_id_Obitos`, `Internados_idInternados`),
  INDEX `fk_tabela_fatos_Casos_idx` (`Casos_idCasos` ASC) VISIBLE,
  INDEX `fk_tabela_fatos_Localidade1_idx` (`Localidade_idLocalidade` ASC) VISIBLE,
  INDEX `fk_tabela_fatos_Recuperados1_idx` (`Recuperados_idRecuperados` ASC) VISIBLE,
  INDEX `fk_tabela_fatos_Obitos1_idx` (`Obitos_id_Obitos` ASC) VISIBLE,
  INDEX `fk_tabela_fatos_Internados1_idx` (`Internados_idInternados` ASC) VISIBLE,
  CONSTRAINT `fk_tabela_fatos_Casos`
    FOREIGN KEY (`Casos_idCasos`)
    REFERENCES `COVID_MG`.`Casos` (`idCasos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabela_fatos_Localidade1`
    FOREIGN KEY (`Localidade_idLocalidade`)
    REFERENCES `COVID_MG`.`Localidade` (`idLocalidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabela_fatos_Recuperados1`
    FOREIGN KEY (`Recuperados_idRecuperados`)
    REFERENCES `COVID_MG`.`Recuperados` (`idRecuperados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabela_fatos_Obitos1`
    FOREIGN KEY (`Obitos_id_Obitos`)
    REFERENCES `COVID_MG`.`Obitos` (`id_Obitos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tabela_fatos_Internados1`
    FOREIGN KEY (`Internados_idInternados`)
    REFERENCES `COVID_MG`.`Internados` (`idInternados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
